<br>
<p> If we include all universities, we can see that there is negative correlation between rent and distance to university is negative, so the further an HMO from a university, the cheaper its rent.</p>
<p>But, if we de-select some universities, the correlation become inconclusive. For example, the scatterplot <b>if we include only all HMOs near UNY (Yogyakarta's second biggest university) the relationship between both of these variables seem random, even positive</b>. There may be other confounding variables that makes this result inconclusive. To analyze deeper, we need a multivariate analysis</p>
### Multivariate Analysis
<p> My undergraduate thesis is about the prices of HMOs and its factors. I use complex methods such as Principal Component Analysis (PCA), Multiple Correspondence Analysis (MCA), and multivariate regression. The results of my thesis may provide a clear answer about the relationship between rent price and distance to university.</p>
<p>I found that the distance to university have a significant negative effect to HMO price, but this effect is small. <b>an extension of 1 Kilometres from the nearest university decrease the monthly rent price by Rp23.000,-</b>. This is small compared to the effect of <b>facilities to rent price which ranges from Rp150.000,- to Rp650.000,-</b>.</p>
<p>This can be learnt for future HMO investors. It may be more profitable to invest in the facilities of the HMO rather than invest in the land near universities. And if they invest a land near university, find the nearest university that its nearest HMO increases in price the nearer it is to said university</p>